#Nirmiti bhopi B51
#DATA TYPES IN PYTHON
#1)integer
num1=20
print(num1,'is the type',type(num1))
#2)float
num2=20.5
print(num2,"is the type",type( num2))
#3)string
name="MUMBAI"
print(name,"is the type",type(name))
#4)boolean
age = 18
result = (age >= 18)
print(result, "is the type", type(result))
#5)list
num=[2,4,6,8,12]
print(num,'is the type',type(num))
#6)tuple
num=(5,10,15,20,25)
print(num,'is the type',type(num))
#7)dictionary
state_city= {'Maharashtra':'nagpur','telangana':'hyderabad','Tamil nadu':'mysore'}
print(state_city,"is the type",type(state_city))
#8)set
num={100,200,300,400,500}
print(num,"is the type",type(num))

